runtime: java11
env: standard
instance_class: F2
runtime_config:
  jdk: openjdk11
#env_variables:
#  SPRING_PROFILES_ACTIVE: application.properties
handlers:
  - url: /.*
    script: this field is required, but ignored

#service_account: civic-matrix-327917.iam.gserviceaccount.com

health_check:
  enable_health_check: False

entrypoint: java -noverify -jar publisher-0.0.1-SNAPSHOT.jar

#liveness_check:
#  path: "/liveness_check"
#  check_interval_sec: 30
#  timeout_sec: 4
#  failure_threshold: 2
#  success_threshold: 2
#readiness_check:
#  path: "/readiness_check"
#  check_interval_sec: 5
#  timeout_sec: 4
#  failure_threshold: 2
#  success_threshold: 2
#  app_start_timeout_sec: 1000
